name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Tests
    uses: zavestudios/platform-pipelines/.github/workflows/python-test.yml@c0aa80bb405fa24ede5ebcf1c40b0be90328386c
    with:
      requirements_file: requirements.txt
      working_directory: backend
      test_command: "python -m pytest -q"

  lint:
    name: Lint
    uses: zavestudios/platform-pipelines/.github/workflows/python-lint.yml@c0aa80bb405fa24ede5ebcf1c40b0be90328386c
    with:
      working_directory: backend
      run_black: false
